### ISSUE TITLE
Tests timeout when run all at once

### ISSUE THREAD

**Issue by capital-G** [capital-G/sc_kernel#14]
There is some issue where after n tests pexpect runs into a timeout.
If the tests are run single they pass and its always another test which fails - even introducing a backoff time did not solve this issue.

A typical error looks like this

```shell
Could not start sclang successfully: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x10dc1feb0>
command: /Applications/SuperCollider.app/Contents/MacOS/sclang
args: [b'/Applications/SuperCollider.app/Contents/MacOS/sclang', b'-i', b'jupyter']
buffer (last 100 chars): "receding error dump is for ERROR: Primitive '_GetLangPort' failed.\r\nFailed.\r\nRECEIVER: NetAddr\r\n\r\n\r\n"
before (last 100 chars): "receding error dump is for ERROR: Primitive '_GetLangPort' failed.\r\nFailed.\r\nRECEIVER: NetAddr\r\n\r\n\r\n"
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 25481
child_fd: 24
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('Welcome to SuperCollider.*')
E
======================================================================
ERROR: test_hello_world (test.test_kernel.ScREPLWrapperTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/scheiba/github/own/sc_kernel/test/test_kernel.py", line 60, in test_hello_world
    repl = ScREPLWrapper(self.sclang_path)
  File "/Users/scheiba/github/own/sc_kernel/sc_kernel/kernel.py", line 190, in __init__
    raise e
  File "/Users/scheiba/github/own/sc_kernel/sc_kernel/kernel.py", line 187, in __init__
    cmd.expect('Welcome to SuperCollider.*', timeout=15)
  File "/Users/scheiba/github/own/sc_kernel/venv/lib/python3.8/site-packages/pexpect/spawnbase.py", line 343, in expect
    return self.expect_list(compiled_pattern_list,
  File "/Users/scheiba/github/own/sc_kernel/venv/lib/python3.8/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/Users/scheiba/github/own/sc_kernel/venv/lib/python3.8/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/Users/scheiba/github/own/sc_kernel/venv/lib/python3.8/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x10dc1feb0>
command: /Applications/SuperCollider.app/Contents/MacOS/sclang
args: [b'/Applications/SuperCollider.app/Contents/MacOS/sclang', b'-i', b'jupyter']
buffer (last 100 chars): "receding error dump is for ERROR: Primitive '_GetLangPort' failed.\r\nFailed.\r\nRECEIVER: NetAddr\r\n\r\n\r\n"
before (last 100 chars): "receding error dump is for ERROR: Primitive '_GetLangPort' failed.\r\nFailed.\r\nRECEIVER: NetAddr\r\n\r\n\r\n"
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 25481
child_fd: 24
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('Welcome to SuperCollider.*')


```

**Comment by capital-G** [comment]
Maybe https://github.com/capital-G/sc_kernel/commit/81886708c1a529f0fb3d93606d55bb7975636b21 fixes this

**Comment by capital-G** [comment]
Seems to be not a problem anymore. This was probably caused by
a) not terminating the repl
b) using too large commands (e.g. for autocomplete)
